### ISSUE TITLE
Consolidate with_devel and other macros for all distros and OSes

### ISSUE THREAD

**Issue by ingvagabund** [gofed/gofed#113]
Golang packages are built for epel7 as well. The with_devel and other macros must take that into account and enable devel and unit-test packages as well.

Let's discuss what is the best resolution for it.

**Comment by bleve** [comment]
Actually, gofed generated spec files are wrong.

spec can not ever generate a result where there is empty %files section. That is what is happening on epel7, because with_devel is made optional. There must always be one %files section left so that package build can fail. Now when %with_devel is set to 0 for epel7 that causes successful rpmbuild but no binary package at all in case of golang package where there is only devel package to generate. That is fundamentally broken. At least one non-optional sub-package must always be present in rpm spec file.

**Comment by ingvagabund** [comment]
Include all three OSes:
- 0%{?fedora}
- 0%{?centos}
- 0%{?rhel}

**Comment by bleve** [comment]
Note: centos also is %rhel

**Comment by bleve** [comment]
That means: 0%{?centos} should only be used inside 0%{?rhel} for centos specific stuff.

**Comment by ingvagabund** [comment]
@bleve so you are saying `%{centos}` is defined only when `%{rhel}` is? Is it documented somewhere? I would consider the `%{centos}` macro separate of rhel even if centos comes from rhel.

**Comment by bleve** [comment]
No. I just say centos always has %{?rhel} defined too.

**Comment by ingvagabund** [comment]
So `if fedora elif centos elif rhel` should do. Thanks.

**Comment by dustymabe** [comment]
I assume this is referring to this section at the top of the gofed generated spec files:

```
%if 0%{?fedora} || 0%{?rhel} == 6
%global with_devel 1
%global with_bundled 0
%global with_debug 1
%global with_check 1
%global with_unit_test 1
%else
%global with_devel 0
%global with_bundled 0
%global with_debug 0
%global with_check 0
%global with_unit_test 0
%endif
```

Can you paste what you suggest this will look like in the future in the `if fedora elif centos elif rhel` case?

**Comment by ingvagabund** [comment]
CentOS:
```sh
$ cat /etc/rpm/macros.dist
# dist macros.

%centos_ver 7
%centos 7
%rhel 7
%dist .el7.centos
%el7 1
```

Fedora:
```sh
$ cat /usr/lib/rpm/macros.d/macros.dist
# dist macros.

%fedora                24
%dist                .fc24
%fc24                1
```

RHEL:
```sh
$ cat /etc/rpm/macros.dist
# dist macros.

%rhel 7
%dist .el7
%el7 1
```

> Can you paste what you suggest this will look like in the future in the if fedora elif centos elif rhel case?

Assumptions:
* devel and unit-test rpms for Fedora, epel7 and centos7 by default
* devel and unit-test rpms are optional (it is up to a maintainer to enable any of them or not)
* debundled in Fedora, epel7 and centos7 by default
* debug info in Fedora, epel7 and centos7 by default
* running tests is optional (run as much of them as possible in %check section, support the tests with CI as well)
* re-usability of the spec file = allow a maintainer to disable any of the devel, unit-test, check and debuginfo parts with minimal modification of the spec file

**Comment by bleve** [comment]
Note: %rhel is set on centos too so there is no reason to do separate %centos check.

And %rhel always matches on centos. So if you need to do rhel only you must do:

%if 0%{?rhel} && 0%{?centos} == 0

If there is nothing real reason to do separation between centos and rhel I suggest: don't do that, it's very hard to get correctly becasue centos is rhel.

**Comment by ingvagabund** [comment]
I would suggest the following structure:
```
# If any of the following macros should be set otherwise,
# you can wrap any of them with the following conditions:
# - %%if 0%%{centos} == 7
# - %%if 0%%{?rhel} == 7
# - %%if 0%%{?fedora} == 23
# Or just test for particular distribution: 
# - %%if 0%%{centos}
# - %%if 0%%{?rhel}
# - %%if 0%%{?fedora}
#
# Be aware, on centos, both %%rhel and %%centos are set. If you want to test
# rhel specific macros, you can use %%if 0%%{?rhel} && 0%%{?centos} == 0 condition.
# (Don't forget to replace double percentage symbol with single one in order to apply a condition)

# Generate devel rpm
%global with_devel 1
# Build project from bundled dependencies
%global with_bundled 0
# Build with debug info rpm
%global with_debug 1
# Run tests in check section
%global with_check 1
# Generate unit-test rpm
%global with_unit_test 1
```

**Comment by ingvagabund** [comment]
@cgwalters WDYT? It should be ok to build all rpms with check and debug info on even through your overlay framework.

**Comment by cgwalters** [comment]
rpmdistro-gitoverlay never runs `%check`.  And I don't know why we wouldn't want debuginfo.

So...sure, seems fine.

**Comment by ingvagabund** [comment]
Fixed by https://github.com/gofed/gofed/commit/576f984ec2c09e3badd8fdfa9440ebe11f1b1d7c.

Can't wait to update all 313 specs.
