### ISSUE TITLE
[RFE] skipp all import paths with %{import_path}/vendor directory

### ISSUE THREAD

**Issue by ingvagabund** [gofed/gofed#117]
E.g. https://github.com/skippbox/kompose/blob/master/Godeps/Godeps.json

**Comment by dustymabe** [comment]
Can you explain this a bit more? which specific examples in the Godeps.json have `%{import_path}/vendor` ?

**Comment by ingvagabund** [comment]
https://github.com/gofed/gofedlib/commit/6af45894b95e34814619c5c2f509669f26f77b42

**Comment by ingvagabund** [comment]
The link was supposed to be a link to https://github.com/skippbox/kompose which contains vendor directories with dependencies.  Instead, I posted a link to Godeps.json. My bad.

Now https://paste.fedoraproject.org/433135/ looks better.

**Comment by ingvagabund** [comment]
Once generated, you can run `gofed fetch --spec` in the same directory as the spec is. It will download correct source code tarball from github.

**Comment by dustymabe** [comment]
> Now https://paste.fedoraproject.org/433135/ looks better.

wow, that does look a lot better. I am not able to reproduce this though. I did a git pull and then re-ran hack/prep.sh and it pulled down the new version of gofedlib, but my gofed still is giving me the same thing almost..

here is the diff: 

``` diff
[vagrant@f24vanilla golang-github-skippbox-kompose]$ diff -U 0 old.spec golang-github-skippbox-kompose.spec 
--- old.spec    2016-09-23 19:46:01.010071563 +0000
+++ golang-github-skippbox-kompose.spec 2016-09-23 19:56:04.650597635 +0000
@@ -1454 +1454 @@
-export GOPATH=$(pwd):$(pwd)/vendor/github.com/fsouza/go-dockerclient/external:$(pwd)/Godeps/_workspace:%{gopath}
+export GOPATH=$(pwd):$(pwd)/vendor/github.com/fsouza/go-dockerclient/external:%{gopath}
@@ -1470 +1470 @@
-for file in $(find . \( -iname "*.go" -or -iname "*.s" \) \! -iname "*_test.go" | grep -v "vendor/github.com/fsouza/go-dockerclient/external" | grep -v "Godeps/_workspace") ; do
+for file in $(find . \( -iname "*.go" -or -iname "*.s" \) \! -iname "*_test.go" | grep -v "vendor/github.com/fsouza/go-dockerclient/external") ; do
@@ -1487 +1487 @@
-for file in $(find . -iname "*_test.go" | grep -v "vendor/github.com/fsouza/go-dockerclient/external" | grep -v "Godeps/_workspace") ; do
+for file in $(find . -iname "*_test.go" | grep -v "vendor/github.com/fsouza/go-dockerclient/external") ; do
@@ -1509 +1509 @@
-export GOPATH=%{buildroot}/%{gopath}:$(pwd)/vendor/github.com/fsouza/go-dockerclient/external:$(pwd)/Godeps/_workspace:%{gopath}
+export GOPATH=%{buildroot}/%{gopath}:$(pwd)/vendor/github.com/fsouza/go-dockerclient/external:%{gopath}
@@ -1543 +1543 @@
-* Thu Sep 22 2016 vagrant - 0-0.1.git8227684
+* Fri Sep 23 2016 vagrant - 0-0.1.git8227684
```

I am running: `gofed repo2spec --detect github.com/skippbox/kompose --commit 822768446621d71ffd02eafd138db0d8ab4a7d0e --with-extra --with-build -f`

**Comment by dustymabe** [comment]
ok. I just wiped out that git repo and did a fresh clone of gofed and the re-ran hack/prep.sh and things seem to be better now.

**Comment by ingvagabund** [comment]
`git pull && hack/prep.sh` should do the trick. The change was carried in submodule, git pull will not pull the change.

**Comment by dustymabe** [comment]
yeah - I did that but for some reason it still had the old behavior until I deleted the repo and did a `git clone && hack/prep.sh`. I'm not sure what was going on.
