### ISSUE TITLE
Compare changes in API with XML file

### ISSUE THREAD

**Issue by fridex** [gofed/gofed#22]
Currently, checking a repo history with apidiff takes way too long. It would be nice to have an option for generating an XML describing API of a project. This XML file would be given as an input for apidiff to be compared with different project version (or comparison of 2 XMLs would be useful as well). This approach would significantly shrink time when checking the repo history (nearly 2 times), since every commit is parsed twice.

**Comment by ingvagabund** [comment]
From 94d5373d9c61cc4a7af3f1e3767c4995226c455c commit, 'gofed apidiff' provides additional options --old-xml and --new-xml which can be used to read symbols from xml file. E.g.

gofed apidiff --old-xml etcd-2.0.6.xml --new-xml etcd-2.0.12 --skip-errors

--skip-errors option is necessary as etcd does not conforms to golang language specification.

etcd-2.0.[6|12].xml files are generated via:

gofed scan-symbols --pure-xml -x -l etcd-2.0.12 --skip-errors > etcd-2.0.12.xml

Xml files generated via scan-imports has empty ipprefix which is used to remove prefix from package import paths, i.e. github.com/coreos/etcd/pkg/testutil => pkg/testutil if prefix is presented.

Plus url attribute or <project> element has changed into ipprefix.
