### ISSUE TITLE
[RFE] Use gcc only in version 5.0.0 and later

### ISSUE THREAD

**Issue by jcajka** [gofed/gofed#25]
gcc-go should be used in version greater or equal to 5.0.0 as some thing are missing prior this version(most noticeably "go" command). Fedora note: From active Fedoras in time of writing only F21 doesn't ship gcc5.

**Comment by ingvagabund** [comment]
All spec files are now generated with:

``` vim
# If go_arches not defined fall through to implicit golang archs
%if 0%{?go_arches:1}
ExclusiveArch:  %{go_arches}
%else
ExclusiveArch:  %{ix86} x86_64 %{arm}
%endif
# If gccgo_arches does not fit or is not defined fall through to golang
%if %{isgccgoarch}
BuildRequires:   gcc-go >= %{gccgo_min_vers}
%else
BuildRequires:   golang
%endif
```

Support for secondary architectures is on all versions of Fedora where go-srpm-macros is in stable repository. However, gcc-go >= %{gccgo_min_vers} condition ensures it is build only on those architectures where gcc-go compiler of required minimal version is provided. I am closing this issue with 5848e1a09ed6a2d991bdf644602e208063a1137b commit.

If there are any missing features or the support is not complete, please open new issue.

Thanks for the request and collaboration
Jan
