### ISSUE TITLE
ExclusiveArch incorrectly used multiple times

### ISSUE THREAD

**Issue by nullr0ute** [gofed/gofed#35]
The spec that's generated by gofed declares ExclusiveArch once towards the top of the spec in the general area and then again in the unit-test section of the spec. 

EG:

``` vim
%if 0%{?with_unit_test}
%package unit-test
Summary:         Unit tests for %{name} package
# If go_arches not defined fall through to implicit golang archs
%if 0%{?go_arches:1}
ExclusiveArch:   %{go_arches}
%else
ExclusiveArch:   %{ix86} x86_64 %{arm}
%endif
```

The usage is incorrect as ExclusiveArch should only ever be declared once, it's only used by rpmbuild on once so the second declaration in the unit-test sub package is unnecessary and generally irrelevant. Please drop the extra declaration in the unit-test.

**Comment by ingvagabund** [comment]
True. It was fixed via 0cded7af2da532e9ecd79f8a278c666cd5ce0f44. Wrote a short article on it here [1].

[1] https://github.com/ingvagabund/articles/blob/master/How-Koji-builds-srpm-and-rpm.md
