### ISSUE TITLE
gofed fails to download GitHub tarball 

### ISSUE THREAD

**Issue by strzibny** [gofed/gofed#67]
`gofed` fails for me when I am trying to use it with GitHub repositories:

```
$ gofed github2spec -r mitchellh -p packer -c f8f7b7a34c1be06058f5aca23a51247db12cdbc5 -f
Repo URL: github.com/packer/mitchellh
Commit: f8f7b7a34c1be06058f5aca23a51247db12cdbc5
Name: golang-github-packer-mitchellh

(1/4) Checking if the package already exists in PkgDB
(2/4) Downloading tarball
Unable to download tarball:
https://github.com/packer/mitchellh/archive/f8f7b7a34c1be06058f5aca23a51247db12cdbc5/mitchellh-f8f7b7a.tar.gz:
2015-10-22 14:33:09 ERROR 404: Not Found.
```

Obviously the path it tries to access does not exists...

**Comment by ingvagabund** [comment]
Hi,

gofed github2spec -p mitchellh -r packer -c f8f7b7a34c1be06058f5aca23a51247db12cdbc5 -f

Project and repository are understood in github terminology. For github.com/mitchellh/packer project is mitchellh and repository packer.

J.

**Comment by strzibny** [comment]
Oh, alright, now that make sense...
