### ISSUE TITLE
gofed appears to not build any packages for rhel7

### ISSUE THREAD

**Issue by agoode** [gofed/gofed#76]
In RHEL 7, with_devel is 0 and nothing is packaged:

```
%if 0%{?fedora} || 0%{?rhel} == 6
%global with_devel 1
%global with_bundled 0
%global with_debug 0
%global with_check 1
%global with_unit_test 1
%else
%global with_devel 0
%global with_bundled 0
%global with_debug 0
%global with_check 0
%global with_unit_test 0
%endif
```

...

```
%if 0%{?with_devel}
%files devel -f devel.file-list
%license LICENSE
%doc README.md CONTRIBUTING.md AUTHORS CONTRIBUTORS
%dir %{gopath}/src/%{provider}.%{provider_tld}/%{project}
%endif

%if 0%{?with_unit_test} && 0%{?with_devel}
%files unit-test-devel -f unit-test-devel.file-list
%license LICENSE
%doc README.md CONTRIBUTING.md AUTHORS CONTRIBUTORS
%endif
```

**Comment by ingvagabund** [comment]
This was left up to user to decide if he wishes to build package with/without devel. Implicitly, RHEL7 has no devel subpackages, everything is bundled. with_bundled macro is supposed to be set to 1 for else branch if the packages builds a golang project and needs dependencies.

**Comment by agoode** [comment]
Regarding RHEL7:
Where is this documented? This is the first I've heard of this policy. I am following https://fedoraproject.org/wiki/Packaging:Guidelines#Bundling_and_Duplication_of_system_libraries and  https://fedoraproject.org/wiki/PackagingDrafts/Go

**Comment by ingvagabund** [comment]
Else branch is not meant for epel7, it is only for RHEL. I don't think there is a document describing packaging policy for RHEL7. We don't provide devel branches for RHEL7 packages as there is no project that would need it.

**Comment by ingvagabund** [comment]
And I would like to have all epel7 golang packages built from dependencies. Thus, another argument for not providing devel packages for epel7/RHEL7. This is hard to document as for epel7 it is not against guildelindes&policies. It has to be decided per case. Value of all with_\* macro is up to user to decide.

**Comment by ingvagabund** [comment]
The macros are now simplified and there is no if-else distro conditions.

**Comment by ingvagabund** [comment]
https://github.com/gofed/gofed/commit/576f984ec2c09e3badd8fdfa9440ebe11f1b1d7c
