### ISSUE TITLE
with_devel and with_bundled for CentOS

### ISSUE THREAD

**Issue by lsm5** [gofed/gofed#88]
default golang spec files have `with_bundled 0` and `with_devel 0` for el7. This results in neither a devel rpm generated nor being able to bundle sources ootb. I'm thinking we should add a 0%{?centos} >= 7 conditional which has `with_bundled 0` and `with_devel 1` if we're strictly following FPC guidelines

**Comment by ingvagabund** [comment]
Resolved with https://github.com/gofed/gofed/issues/113.
